name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: rpg_test
          postgresql user: postgres
          postgresql password: postgres
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.11'
      #- run: cp secrets.dist.sh secrets.sh
      - run: MIX_ENV=test mix deps.get
      - run: MIX_ENV=test mix test
      - run: MIX_ENV=test mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


